import React from "react";
import OurPhilosophy from "../components/corporateGovernance/OurPhilosophy";
import CorporateBanner from "../components/corporateGovernance/CorporateBanner";
import GloballyCertified from "../components/GloballyCertified";
import { getPageData } from "@/_lib/pageData.fetch";
import { getData } from "@/_lib/getData.fetch";
import OurCodeAndPolicies from "../components/corporateGovernance/OurCodeAndPolicies";
import MeetMinds from "../components/who-we-are/MeetMinds";
import ContactBanner from "../components/ContactBanner";
import DirectorsNcommittees from "../components/corporateGovernance/DirectorsNcommittees";

export const dynamic = "force-dynamic";

const page = async () => {
  const data = await getPageData("/pages/by-slug/ethics");
  const globallyCertifiedData = await getData(
    "/globally-certified-datas?populate=*"
  );
  const {
    // section_one,
    // section_two,
    // section_three,
    // section_four,
  } = data;

  console.log(data);

  const section_one = {
    id: 1,
    title: "Corporate Governance",
    description:
      "We deliver sustainable chemical solutions that power innovation across global industries.",
    btnTitle: "Our Code and Policies",
    btnLink: "/solutions",
    image: {
      id: 560,
      documentId: "v9vsi5urwetsioe5jl34slr1",
      url: "https://d2sslj1veyp2s3.cloudfront.net/DJI_0094_a9bdcf4bc6.jpg",
      alternativeText: null,
      mime: "image/jpeg",
      ext: ".jpg",
      isUrlSigned: false,
    },
    mobImage: {
      id: 560,
      documentId: "v9vsi5urwetsioe5jl34slr1",
      url: "https://d2sslj1veyp2s3.cloudfront.net/DJI_0094_a9bdcf4bc6.jpg",
      alternativeText: null,
      mime: "image/jpeg",
      ext: ".jpg",
      isUrlSigned: false,
    },
  };
  const section_two = {
    id: 1,
    heading: "Our Philosophy",
    description:
      " Aarti Industries Limited's (hereinafter may be referred as ‘the Company’ or ‘AIL’ or ‘Aarti’) business practices have been governed by our values of Care, Integrity and Excellence. In this way, we want to be a reliable partner for our customers, suppliers, employees and shareholders. <br /><br /> We have established ourselves as a well-governed corporate with an excellent reputation as ‘Global Partner of Choice’ - a precious recognition that we want to protect, sustain and develop. <br /><br /> We want to continue grow profitably with a strong focus on productivity. Acting irresponsibly can lead to considerable damage. For this reason, compliance with applicable rules, regulations, codes, guidelines and policies is regarded as a permanent feature of our corporate culture.",

    image: {
      id: 556,
      documentId: "pkg8ybvzn7v3lyx63ss6rema",
      url: "https://d2sslj1veyp2s3.cloudfront.net/DJI_0085_047f398723.JPG",
      alternativeText: null,
      mime: "image/jpeg",
      ext: ".JPG",
      isUrlSigned: false,
    },
    mobImage: {
      id: 556,
      documentId: "pkg8ybvzn7v3lyx63ss6rema",
      url: "https://d2sslj1veyp2s3.cloudfront.net/DJI_0085_047f398723.JPG",
      alternativeText: null,
      mime: "image/jpeg",
      ext: ".JPG",
      isUrlSigned: false,
    },
  };
  const section_three = {
    id: 1,
    heading: "Our Code and Policies",
    description:
      "All Our Policies are Under Revision and will be Updated Soon.",
    policies: [
      {
        id: 1,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
      {
        id: 2,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
      {
        id: 3,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
      {
        id: 4,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
      {
        id: 5,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
      {
        id: 6,
        heading: "Our Code and Policies",
        link: "/solutions",
      },
    ],
  };
  const section_four = {
    id: 1,
    sectionTitle: "Meet the Minds Behind Our Growth",
    management_boards: [
      {
        id: 9,
        documentId: "jggbwxi0chvgfxfqsid5zfpa",
        name: "Shri Chandrakant Gogri",
        designation: "Chairman Emeritus",
        bio: " Founder and principal promoter of Aarti Group, Shri Gogri is a Chemical Engineer from UDCT. He transformed Aarti from a single unit into a leading chemical enterprise, with expertise spanning operations, projects, marketing, and finance. Retired as Chairman in 2012, he now serves as Chairman Emeritus. He received UDCT’s Distinguished Alumnus Award in 1995 for his entrepreneurial achievements along with several prestigious awards, including the Chemexcil Lifetime Achievement Award in 2025, the Lifetime Contribution Award at the Chemical and Petrochemical Awards by FICCI, the ICC’s D.M. Trivedi Lifetime Achievement Award, the Lala Shriram National Award for Leadership in the Chemical Industry, and the Lifetime Achievement Award from the Gujarat Dyestuff Manufacturers Association (GDMA).",
        order: null,
        createdAt: "2025-11-15T09:21:03.312Z",
        updatedAt: "2025-11-16T15:50:12.890Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 1,
        documentId: "fyy3xit1v8hffl4n9716em5z",
        name: "Shri Rajendra V. Gogri",
        designation: "Chairman & Managing Director",
        bio: "A founding member of Aarti Industries, Shri Rajendra V. Gogri became Chairman in 2012 after serving nearly two decades as Managing Director. A rank holder from UDCT and a Master’s in Chemical Engineering from the USA, he combines deep technical expertise with financial and commercial insight. He was awarded UDCT’s Distinguished Alumnus Award in 1995, ICC’s Lala Shriram National Award in 2019, and the Hurun Most Respected Entrepreneur of the Year – India in the same year.",
        order: null,
        createdAt: "2025-11-05T07:21:56.653Z",
        updatedAt: "2025-11-16T15:50:52.340Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 12,
        documentId: "w7aq8gipha1veou0nhc4tebn",
        name: "Shri Rashesh C. Gogri",
        designation: "Vice Chairman & Managing Director",
        bio: "Shri Rashesh C. Gogri, a second-generation entrepreneur, joined Aarti’s Board in 1997 and has served as Vice Chairman & Managing Director since 2012. A production engineering graduate from Mumbai University, he brings sharp business acumen and strategic vision. He leads AIL’s business strategy, sales, and procurement, driving the company’s expansion and project execution across global markets.",
        order: null,
        createdAt: "2025-11-15T09:34:12.108Z",
        updatedAt: "2025-11-16T15:51:59.690Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 17,
        documentId: "kqldu98zvg79nnjqu2428z0h",
        name: "Shri Suyog Kotecha",
        designation: "CEO and Executive Director",
        bio: "Shri Suyog Kotecha brings over 20 years of experience across the chemical and energy sectors. He previously led strategy and new business initiatives for Reliance's petrochemicals division and was a Partner at McKinsey & Company, heading its Chemicals Practice. His global experience spans Shell, Sulzer Chemtech, and roles across Asia and Europe. Suyog holds a Bachelor’s from UDCT, a Master’s from Universiteit Twente, and an MBA from ISB Hyderabad. He blends technical depth with strategic insight to drive growth and transformation.",
        order: null,
        createdAt: "2025-11-15T09:47:12.668Z",
        updatedAt: "2025-11-16T15:51:09.837Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 5,
        documentId: "a9v0oufrn0sv7hphtwxwnsal",
        name: "Shri Renil R. Gogri",
        designation: "Vice Chairman",
        bio: "Renil Gogri, Vice-Chairman of Aarti Industries and an alumnus of IIT Bombay, has driven the company's growth since joining in 2009 and assuming the role of  Executive Director in 2012. Recognised for his expertise in manufacturing, project execution, technology, and talent management, he has positioned AIL as a leader in the chemical industry. He oversees production, IT, sustainability, and safety, using strategic insights and a practical approach to maintain operational excellence. His ongoing focus on process development and upskilling encourages innovation and fosters a strong organisational culture.",
        order: null,
        createdAt: "2025-11-13T10:21:42.873Z",
        updatedAt: "2025-11-16T15:51:44.150Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 19,
        documentId: "qiiv63k67dgqheup39f0ak57",
        name: "Shri Lalitkumar Naik",
        designation: "Independent Director",
        bio: "Shri Lalitkumar S. Naik is a B.Tech in Chemical Engineering from IIT Kanpur and holds a PGDM from IIM Ahmedabad. With over 25 years of leadership experience, he has held senior roles across the chemicals, building materials, and nutrition sectors.",
        order: null,
        createdAt: "2025-11-15T09:51:01.164Z",
        updatedAt: "2025-11-16T15:50:33.737Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 21,
        documentId: "ofggq9kw3nolkdk43if0splb",
        name: "Prof. Aniruddha B. Pandit",
        designation: "Independent Director",
        bio: "Prof. Aniruddha B. Pandit is Vice Chancellor of the Institute of Chemical Technology and a globally recognised academic in chemical engineering. With extensive teaching and research experience, he has guided over 60 Ph.D. students and authored numerous international publications and patents. He is a Fellow of all Indian science academies and the U.S. National Academy of Engineering.",
        order: null,
        createdAt: "2025-11-15T09:52:53.044Z",
        updatedAt: "2025-11-16T15:49:38.447Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 23,
        documentId: "nbn7fsem78fv1rw8r8kbcpr8",
        name: "Shri Shekhar Khanolkar",
        designation: "Independent Director",
        bio: "Shri Shekhar Khanolkar is a seasoned business leader with over 30 years of experience across India, Europe, and the U.S. He has held leadership roles at Cyanamid India, RPG Enterprises, BASF India, and Navin Fluorine International, where he led the global CDMO business. A Chemical Engineer with an MBA, he has also completed advanced management studies at Harvard Business School.",
        order: null,
        createdAt: "2025-11-15T09:54:20.721Z",
        updatedAt: "2025-11-16T15:51:27.697Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
      {
        id: 25,
        documentId: "fncaosd8u8mmqqmw4p8iwswt",
        name: "Shri Belur Krishnamurthy Sethuram",
        designation: "Independent Director",
        bio: "Shri B. K. Sethuram brings over 38 years of experience in scaling B2B businesses and mentoring future leaders. He has held leadership roles at Celanese, Dow Chemicals, and other domestic firms. An IIT Madras graduate, he also holds an MS and an MBA, and has completed executive programs at Sasin and the Kellogg School of Management. A certified CEO coach, he is also active in social impact through Social Venture Partners.",
        order: null,
        createdAt: "2025-11-15T09:55:27.937Z",
        updatedAt: "2025-11-16T15:49:55.489Z",
        publishedAt: null,
        locale: null,
        image: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
        mobImage: {
          id: 528,
          documentId: "oa2o0jhh8u57zmas7dqmsb41",
          url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
          alternativeText: null,
          mime: "image/png",
          ext: ".png",
          isUrlSigned: false,
        },
      },
    ],
  };
  const section_five = {
    id: 1,
    title: "We’d love to hear from you. Connect with our team today",
    ctaButton: {
      id: 138,
      title: "Contact Us",
      link: "#",
    },
  };

  const section_six = [
    {
      id: 1,
      category: "Independent Directors",
      management_boards: [
        {
          id: 9,
          documentId: "jggbwxi0chvgfxfqsid5zfpa",
          name: "Shri Chandrakant Gogri",
          designation: "Chairman Emeritus",
          bio: " Founder and principal promoter of Aarti Group, Shri Gogri is a Chemical Engineer from UDCT. He transformed Aarti from a single unit into a leading chemical enterprise, with expertise spanning operations, projects, marketing, and finance. Retired as Chairman in 2012, he now serves as Chairman Emeritus. He received UDCT’s Distinguished Alumnus Award in 1995 for his entrepreneurial achievements along with several prestigious awards, including the Chemexcil Lifetime Achievement Award in 2025, the Lifetime Contribution Award at the Chemical and Petrochemical Awards by FICCI, the ICC’s D.M. Trivedi Lifetime Achievement Award, the Lala Shriram National Award for Leadership in the Chemical Industry, and the Lifetime Achievement Award from the Gujarat Dyestuff Manufacturers Association (GDMA).",
          order: null,
          createdAt: "2025-11-15T09:21:03.312Z",
          updatedAt: "2025-11-16T15:50:12.890Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 1,
          documentId: "fyy3xit1v8hffl4n9716em5z",
          name: "Shri Rajendra V. Gogri",
          designation: "Chairman & Managing Director",
          bio: "A founding member of Aarti Industries, Shri Rajendra V. Gogri became Chairman in 2012 after serving nearly two decades as Managing Director. A rank holder from UDCT and a Master’s in Chemical Engineering from the USA, he combines deep technical expertise with financial and commercial insight. He was awarded UDCT’s Distinguished Alumnus Award in 1995, ICC’s Lala Shriram National Award in 2019, and the Hurun Most Respected Entrepreneur of the Year – India in the same year.",
          order: null,
          createdAt: "2025-11-05T07:21:56.653Z",
          updatedAt: "2025-11-16T15:50:52.340Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 12,
          documentId: "w7aq8gipha1veou0nhc4tebn",
          name: "Shri Rashesh C. Gogri",
          designation: "Vice Chairman & Managing Director",
          bio: "Shri Rashesh C. Gogri, a second-generation entrepreneur, joined Aarti’s Board in 1997 and has served as Vice Chairman & Managing Director since 2012. A production engineering graduate from Mumbai University, he brings sharp business acumen and strategic vision. He leads AIL’s business strategy, sales, and procurement, driving the company’s expansion and project execution across global markets.",
          order: null,
          createdAt: "2025-11-15T09:34:12.108Z",
          updatedAt: "2025-11-16T15:51:59.690Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 17,
          documentId: "kqldu98zvg79nnjqu2428z0h",
          name: "Shri Suyog Kotecha",
          designation: "CEO and Executive Director",
          bio: "Shri Suyog Kotecha brings over 20 years of experience across the chemical and energy sectors. He previously led strategy and new business initiatives for Reliance's petrochemicals division and was a Partner at McKinsey & Company, heading its Chemicals Practice. His global experience spans Shell, Sulzer Chemtech, and roles across Asia and Europe. Suyog holds a Bachelor’s from UDCT, a Master’s from Universiteit Twente, and an MBA from ISB Hyderabad. He blends technical depth with strategic insight to drive growth and transformation.",
          order: null,
          createdAt: "2025-11-15T09:47:12.668Z",
          updatedAt: "2025-11-16T15:51:09.837Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 5,
          documentId: "a9v0oufrn0sv7hphtwxwnsal",
          name: "Shri Renil R. Gogri",
          designation: "Vice Chairman",
          bio: "Renil Gogri, Vice-Chairman of Aarti Industries and an alumnus of IIT Bombay, has driven the company's growth since joining in 2009 and assuming the role of  Executive Director in 2012. Recognised for his expertise in manufacturing, project execution, technology, and talent management, he has positioned AIL as a leader in the chemical industry. He oversees production, IT, sustainability, and safety, using strategic insights and a practical approach to maintain operational excellence. His ongoing focus on process development and upskilling encourages innovation and fosters a strong organisational culture.",
          order: null,
          createdAt: "2025-11-13T10:21:42.873Z",
          updatedAt: "2025-11-16T15:51:44.150Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
      ],
    },
    {
      id: 18,
      category: "Committees",
      management_boards: [
        {
          id: 21,
          documentId: "ofggq9kw3nolkdk43if0splb",
          name: "Prof. Aniruddha B. Pandit",
          designation: "Independent Director",
          bio: "Prof. Aniruddha B. Pandit is Vice Chancellor of the Institute of Chemical Technology and a globally recognised academic in chemical engineering. With extensive teaching and research experience, he has guided over 60 Ph.D. students and authored numerous international publications and patents. He is a Fellow of all Indian science academies and the U.S. National Academy of Engineering.",
          order: null,
          createdAt: "2025-11-15T09:52:53.044Z",
          updatedAt: "2025-11-16T15:49:38.447Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 23,
          documentId: "nbn7fsem78fv1rw8r8kbcpr8",
          name: "Shri Shekhar Khanolkar",
          designation: "Independent Director",
          bio: "Shri Shekhar Khanolkar is a seasoned business leader with over 30 years of experience across India, Europe, and the U.S. He has held leadership roles at Cyanamid India, RPG Enterprises, BASF India, and Navin Fluorine International, where he led the global CDMO business. A Chemical Engineer with an MBA, he has also completed advanced management studies at Harvard Business School.",
          order: null,
          createdAt: "2025-11-15T09:54:20.721Z",
          updatedAt: "2025-11-16T15:51:27.697Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 25,
          documentId: "fncaosd8u8mmqqmw4p8iwswt",
          name: "Shri Belur Krishnamurthy Sethuram",
          designation: "Independent Director",
          bio: "Shri B. K. Sethuram brings over 38 years of experience in scaling B2B businesses and mentoring future leaders. He has held leadership roles at Celanese, Dow Chemicals, and other domestic firms. An IIT Madras graduate, he also holds an MS and an MBA, and has completed executive programs at Sasin and the Kellogg School of Management. A certified CEO coach, he is also active in social impact through Social Venture Partners.",
          order: null,
          createdAt: "2025-11-15T09:55:27.937Z",
          updatedAt: "2025-11-16T15:49:55.489Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 25,
          documentId: "fncaosd8u8mmqqmw4p8iwswt",
          name: "Shri Belur Krishnamurthy Sethuram",
          designation: "Independent Director",
          bio: "Shri B. K. Sethuram brings over 38 years of experience in scaling B2B businesses and mentoring future leaders. He has held leadership roles at Celanese, Dow Chemicals, and other domestic firms. An IIT Madras graduate, he also holds an MS and an MBA, and has completed executive programs at Sasin and the Kellogg School of Management. A certified CEO coach, he is also active in social impact through Social Venture Partners.",
          order: null,
          createdAt: "2025-11-15T09:55:27.937Z",
          updatedAt: "2025-11-16T15:49:55.489Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
        {
          id: 25,
          documentId: "fncaosd8u8mmqqmw4p8iwswt",
          name: "Shri Belur Krishnamurthy Sethuram",
          designation: "Independent Director",
          bio: "Shri B. K. Sethuram brings over 38 years of experience in scaling B2B businesses and mentoring future leaders. He has held leadership roles at Celanese, Dow Chemicals, and other domestic firms. An IIT Madras graduate, he also holds an MS and an MBA, and has completed executive programs at Sasin and the Kellogg School of Management. A certified CEO coach, he is also active in social impact through Social Venture Partners.",
          order: null,
          createdAt: "2025-11-15T09:55:27.937Z",
          updatedAt: "2025-11-16T15:49:55.489Z",
          publishedAt: null,
          locale: null,
          image: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
          mobImage: {
            id: 528,
            documentId: "oa2o0jhh8u57zmas7dqmsb41",
            url: "https://d2sslj1veyp2s3.cloudfront.net/dd5be70ab4320f600af1df2ea21ce518ed46e958_f315811143.png",
            alternativeText: null,
            mime: "image/png",
            ext: ".png",
            isUrlSigned: false,
          },
        },
      ],
    },
  ];

  return (
    <div>
      {section_one && <CorporateBanner data={section_one} />}

      {section_two && <OurPhilosophy data={section_two} />}

      {section_three && <OurCodeAndPolicies data={section_three} />}

      {section_four && (
        <div className="mt-[72px] md:mt-[120px]">
          <MeetMinds data={section_four} />
        </div>
      )}

      {section_five && <ContactBanner data={section_five} />}

      {section_six && <DirectorsNcommittees data={section_six} />}

      <section className="pb-30 w-full">
        {section_five && <ContactBanner data={section_five} />}
      </section>
      {/*       

      {section_three && <GlobalInnovation data={section_three} />} */}

      {globallyCertifiedData && (
        <GloballyCertified itemsData={globallyCertifiedData} />
      )}
    </div>
  );
};

export default page;
